site_name: pyncbt
site_url: https://JoaoLeroy.github.io/pyncbt/
theme:
  name: material # Visual moderno
  palette:
    primary: indigo
    accent: indigo
  features:
    - content.code.copy # Botão de copiar código

plugins:
  - search
  - mkdocstrings: # Gera documentação do seu código automaticamente
      default_handler: python
      handlers:
        python:
          paths: [scr] # Onde está o seu código.py
