
site_name: pyncbt
site_url: https://joaoleroy.github.io/pyncbt/  
repo_url: https://github.com/JoaoLeroy/pyncbt
repo_name: JoaoLeroy/pyncbt

theme:
  name: material
  language: pt

nav:
  - Início: index.md
