site_name: pyncbt
site_url: https://JoaoLeroy.github.io/pyncbt/
repo_url: https://github.com/JoaoLeroy/pyncbt
site_description: Biblioteca de alto desempenho para manipulação de arquivos NBT.

theme:
  name: material
  language: pt-BR
  logo: docs/img/pyncbt-logo.png # Crie um logo e coloque nesta pasta
  favicon: logo/favicon.ico
  palette:
    - scheme: default # Modo claro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Mudar para modo escuro
    - scheme: slate # Modo escuro
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Mudar para modo claro
  features:
    - navigation.tabs # Menu no topo igual sites grandes
    - navigation.sections
    - navigation.top # Botão de "voltar ao topo"
    - content.code.copy # Botão de copiar código
    - content.code.annotate

nav:
  - Início: index.md
  - Referência da API: api.md
  
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("scr")
          paths: [scr]
          options:
            show_source: true # Mostra o código-fonte na documentação
            show_type_annotations: true
