[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyncbt"
version = "0.1.1"
authors = [
    { name = "Joao Pedro Mendes Leroy", email = "jpmleroy24@gmail.com" },
]
description = "A Python library for Non-iterative Correlation-based Tuning (NCbT)."
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.7"
dependencies = [
    "numpy",
    "scipy",
    "control",
]

[project.urls]
Homepage = "https://github.com/JoaoLeroy/pyncbt"
Repository = "https://github.com/JoaoLeroy/pyncbt.git"
Documentation = "https://JoaoLeroy.github.io/pyncbt"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["pyncbt"]
